[package]
name = "codey-market-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[lib]
name = "codey_market_server"
doctest = false

[lints]
workspace = true

[dependencies]
argon2 = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
futures-util = { workspace = true }
rusqlite = { workspace = true }
postgres = { workspace = true }
reqwest = { workspace = true }
qrcode = { workspace = true }
ring = { workspace = true }
rsa = { workspace = true }
schemars = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "net", "signal"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
ulid = { workspace = true }
url = { workspace = true }
yaml-rust2 = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
tempfile = { workspace = true }
